import './globals.css'
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css'

export const metadata = {
  title: 'Sulok Digital Pvt Limited',
  description: 'Generated by create next app',
  icons:{
    icon:'/logo.jpg'
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
